AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  QuickBooks Online Invoice Automation

  SAM application with two Lambda functions:
  1. SendInvoicesFunction - Sends today's invoices daily
  2. CreateInvoicesFunction - Creates monthly invoices from recurring transactions

Globals:
  Function:
    Timeout: 120
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        QBO_SECRET_NAME: QBO/10000
        MSGRAPH_SECRET_NAME: MsGraph/10000
        CLICKUP_SECRET_NAME: ClickUp/10000
        ROBOCORP_API_SECRET_NAME: RoboCorp/10000/ClientAPIKeys
        BOOKKEEPER_EMAIL: whartman@automatapracdev.com
        EXCLUDED_CUSTOMERS: "10001 - AICPA"
        SENDER_EMAIL: robotarmy@automatapracdev.com
        DYNAMODB_TABLE_ROBOCORP_CLIENTS: "Robocorp_Client_Org_Workspace_IDs"
        MS_GRAPH_HOSTNAME: automatapracdev.sharepoint.com
        # BILLING_REFERENCE_DATE: "2025-11-01"  # Optional: Uncomment to override billing period (format: YYYY-MM-DD)

Resources:
  # Lambda function to send daily invoices
  SendInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: send_invoices.app.lambda_handler
      Description: Sends QuickBooks Online invoices created today and emails summary
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:UpdateSecret
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:10000/QBO*"
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:10000/MsGraph*"
      Events:
        # Daily schedule - runs at 5 PM Pacific (1 AM UTC next day)
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
            Description: Run daily at 5 AM Pacific to send today's invoices
            Enabled: false  # Set to true when ready to activate
        # API Gateway endpoint for manual triggering
        ManualTrigger:
          Type: Api
          Properties:
            Path: /send-invoices
            Method: post

  # Lambda function to create monthly invoices
  CreateInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: create_invoices.app.lambda_handler
      Description: Creates QuickBooks Online invoices from recurring transactions monthly
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:UpdateSecret
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:10000/QBO*"
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:10000/MsGraph*"
      Events:
        # Monthly schedule - runs on 4th of each month at 9 AM Pacific (5 PM UTC)
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 17 4 * ? *)
            Description: Run on 4th of each month at 9 AM Pacific to create invoices
            Enabled: false  # Set to true when implementation is complete
        # API Gateway endpoint for manual triggering
        ManualTrigger:
          Type: Api
          Properties:
            Path: /create-invoices
            Method: post

Outputs:
  SendInvoicesFunctionArn:
    Description: "Send Invoices Lambda Function ARN"
    Value: !GetAtt SendInvoicesFunction.Arn

  CreateInvoicesFunctionArn:
    Description: "Create Invoices Lambda Function ARN"
    Value: !GetAtt CreateInvoicesFunction.Arn

  ApiEndpoint:
    Description: "API Gateway endpoint URL for manual triggering"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  SendInvoicesManualUrl:
    Description: "POST to this URL to manually trigger invoice sending"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-invoices"

  CreateInvoicesManualUrl:
    Description: "POST to this URL to manually trigger invoice creation"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-invoices"
